use_frameworks!

platform :ios, '10.0'

target 'zzylib_Example' do
  pod 'zzylib', :path => '../'

  target 'zzylib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
