source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.cnmlsz.com/mlhk/mlhkspecs.git'
source 'https://github.com/zhengzeyou/zzySpecs.git'

use_frameworks!

platform :ios, '10.0'

target 'zzylib_Example' do
  pod 'zzylib', :path => '../'
  target 'zzylib_Tests' do
    inherit! :search_paths
  end
end
